### ISSUE TITLE
New releases still need to be tagged

### ISSUE THREAD

**Issue by kghbln** [pediapress/mwlib#57]
When installing "mwlib" one still gets 0.15.15 as opposed to 0.15.16 or 0.15.17 which is the latest version. Thanks and cheers.

**Comment by kghbln** [comment]
Ah, I guess the files will also have to be uploaded to e.g. http://pypi.pediapress.com/simple/mwlib/

**Comment by berashith** [comment]
Ditto. Wanting to try versions beyond 0.15.15

**Comment by v0lk3r** [comment]
I just released 0.15.19
