### ISSUE TITLE
gevent.coros missing

### ISSUE THREAD

**Issue by jmsaltzman** [pediapress/mwlib#63]
Semaphore from gevent.coros is used in fetch.py and sapi.py, but Semaphore is in gevent.lock.

This causes the first line of the test to fail:
mw-zip -c :en -o test.zip Acdc Number
(from http://mwlib.readthedocs.io/en/latest/installation.html#test-install)

Replacing 'coros' with 'lock' fixes it.

This may be an issue with gevent not deprecating coros nicely but thought you should know :)

**Comment by v0lk3r** [comment]
fixed in the latest version
